AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  personal-portfolio-app

  Sample SAM Template for personal-portfolio-app
  
Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x

Resources:
  ManageProjectsApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: getProjects.lambdaHandler
      Architectures:
        - x86_64
      Events:
        GetProjectsApi:
          Type: Api
          Properties:
            Path: /projects
            Method: get
        PostProjectsApi:
          Type: Api
          Properties:
            Path: /projects
            Method: post
        DeleteProjectsApi:
          Type: Api
          Properties:
            Path: /projects
            Method: delete
        PutProjectsApi:
          Type: Api
          Properties:
            Path: /projects
            Method: put

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - manageProjects.ts

